### HW04

#### 用物件導向建立stander scaler

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
scaler.mean_

array([ 0.5,  0.5])

In [6]:
scaler.var_

array([ 0.25,  0.25])

In [7]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [8]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

#### 參考StandardScaler仿寫一個 MyStandardScaler

In [12]:
import  numpy  as  np

In [13]:
class Mystandardscaler():
    def _init_(self):
        self.mean_ = None
        self.std_ = None
        
    def fit(self, x):
        self.mean_ = np.mean(x,axis=0)
        self.std_ = np.std(x, axis=0)
        
    def transform(self, x):
        return (x-self.mean_)/self.std_
    
    def fit_transform(self,x):
        self.fit(x)
        return self.transform(x)

In [19]:
Myscaler =Mystandardscaler()

In [20]:
Myscaler.fit(data)

In [21]:
Myscaler.mean_

array([ 0.5,  0.5])

In [22]:
Myscaler.std_

array([ 0.5,  0.5])

In [23]:
Myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [27]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])